require_relative 'client_input_descriptions'
require_relative 'user_input_response'
require_relative 'session_identification'

module DaVinciPASTestKit
  # abstract test, needs to be extended to include a version-specific URLs module
  class AbstractModificationSubmitTest < Inferno::Test
    include UserInputResponse
    include SessionIdentification

    id :pas_client_modification_submit_test
    title 'Client submits a claim using the $submit operation'
    description %(
      Inferno will wait for a prior authorization submission request
      from the client. Upon receipt, Inferno will generate and send a
      response in which the payer authorizes items that differ from those
      that were requested (a "payer modification").
    )

    input :modification_json_response,
          title: 'Claim modified response JSON',
          type: 'textarea',
          optional: true,
          description: %(
            If provided, this JSON will be sent in response to $submit requests during this test
            to indicate that the payer authorized items that differ from those requested.
            It will be updated to make creation timestamps current.
            If not provided, a payer modification response will be generated from the submitted Claim,
            marking each item as modified (adjudication status A6) and adding a corresponding
            `ClaimResponse.addItem` describing what was actually authorized.
            In either case, the response will be validated against the PAS Response Bundle profile.
          )
    input :client_id,
          title: 'Client Id',
          type: 'text',
          optional: true,
          locked: true,
          description: INPUT_CLIENT_ID_LOCKED
    input :session_url_path,
          title: 'Session-specific URL path extension',
          type: 'text',
          optional: true,
          locked: true,
          description: INPUT_SESSION_URL_PATH_LOCKED

    submit_respond_with :modification_json_response

    run do
      if user_inputted_response? :modification_json_response
        assert_valid_json modification_json_response,
                          'Input "Claim modified response JSON" must be valid JSON'
      else
        add_message('info', %(
          No modified response provided in input '#{input_title(:modification_json_response)}'. Any responses to
          $submit requests will be generated by Inferno from the submitted Claim.
        ))
      end

      wait_identifier = session_wait_identifier(client_id, session_url_path)
      submit_endpoint = session_endpont_url(:submit, client_id, session_url_path)

      wait(
        identifier: wait_identifier,
        message: %(
          **Payer Modification Workflow Test**:

          Submit a PAS request to

          `#{submit_endpoint}`

          If the optional '**#{input_title(:modification_json_response)}**' input is populated, it will
          be returned, updated with current timestamps. Otherwise, a payer modification response will
          be generated by Inferno using the received Claim.
        )
      )
    end
  end
end
