require_relative '../parameters_helper'

module DaVinciPASTestKit
  module ResponseGenerator
    include ParametersHelper

    def mock_id_only_notification_bundle(submit_response, subscription_reference, subscription_topic,
                                         ig_version = 'v2.0.1')
      notification_timestamp = Time.now.utc
      mock_notification_bundle = build_mock_notification_bundle(notification_timestamp, subscription_reference,
                                                                subscription_topic, submit_response, 'id-only', nil,
                                                                ig_version)
      mock_notification_bundle.to_json
    end

    def mock_full_resource_notification_bundle(submit_response, subscription_reference, subscription_topic, decision,
                                               ig_version = 'v2.0.1')
      notification_timestamp = Time.now.utc
      mock_notification_bundle = build_mock_notification_bundle(notification_timestamp, subscription_reference,
                                                                subscription_topic, submit_response, 'full-resource',
                                                                decision, ig_version)
      mock_notification_bundle.to_json
    end

    def mock_response_bundle(request_bundle, operation, decision, claim_response_uuid = nil, ig_version = 'v2.0.1')
      mocked_timestamp = Time.now.utc
      response = build_mock_response_bundle(request_bundle, operation, decision, mocked_timestamp,
                                            claim_response_uuid, ig_version)
      return nil unless response.present?

      # For v2.2.0 inquire operations, wrap the Bundle in a Parameters resource
      response = wrap_bundle_in_parameters(response) if ig_version == 'v2.2.0' && operation == 'inquire'

      response.to_json
    end

    # update things that tester cannot get right themselves
    # - timestamps on the Bundle and ClaimResponse (can't predict the processing time)
    # - reference to the submitted Claim (may not have control of created id). NOTE: this is likely
    #   incomplete - when the Claim is included, there are other things that
    #   need to be in the Bundle that may also not be controlled
    def update_tester_provided_response(user_inputted_response, claim_full_url, operation, ig_version = 'v2.0.1')
      response_resource = FHIR.from_contents(user_inputted_response)
      return user_inputted_response unless response_resource.present?

      # For v2.2.0 inquire responses, wrap user's Bundle in Parameters if needed
      if ig_version == 'v2.2.0' && operation == 'inquire' && response_resource.is_a?(FHIR::Bundle)
        response_resource = wrap_bundle_in_parameters(response_resource)
      end

      # Extract Bundle(s) for updating
      bundles_to_update = []
      is_parameters = response_resource.resourceType == 'Parameters'

      if is_parameters
        bundles_to_update = extract_bundles_from_pas_inquiry_response_parameters(response_resource)
      elsif response_resource.is_a?(FHIR::Bundle)
        bundles_to_update = [response_resource]
      else
        return user_inputted_response
      end

      now = Time.now.utc
      bundles_to_update.each do |response_bundle|
        update_response_bundle(response_bundle, claim_full_url, now, ig_version)
      end

      response_resource.to_json
    end

    # update things that tester cannot get right themselves
    # - reference to the ClaimResponse in the case that it is generated by Inferno.
    #   If the tester provided the ClaimResponse, they are responsible for aligning
    #   the notification with it.
    # - notification timestamps
    def update_tester_provided_notification(user_inputted_notification, generated_claim_response_uuid)
      now = Time.now.utc

      notification_bundle = FHIR.from_contents(user_inputted_notification)
      subscription_status_entry = notification_bundle&.entry&.find { |e| e.resource&.resourceType == 'Parameters' }
      subscription_status_resource = subscription_status_entry&.resource
      event_parameter = subscription_status_resource&.parameter&.find { |p| p.name == 'notification-event' }

      if generated_claim_response_uuid.present?
        claim_response_full_url = "urn:uuid:#{generated_claim_response_uuid}"
        focus_part = event_parameter&.part&.find { |pt| pt.name == 'focus' }
        if focus_part.present?
          existing_claim_response_reference = focus_part.valueReference&.reference
          focus_part.valueReference.reference = claim_response_full_url
          update_tester_provided_notification_claim_response_entry(notification_bundle,
                                                                   generated_claim_response_uuid,
                                                                   claim_response_full_url,
                                                                   existing_claim_response_reference)

        end
      end

      timestamp_part = event_parameter&.part&.find { |pt| pt.name == 'timestamp' }
      timestamp_part.valueInstant = now.iso8601 if timestamp_part.present?
      notification_bundle.timestamp = now.iso8601 if notification_bundle.timestamp.present?

      notification_bundle.to_json
    end

    private

    # if there's a ClaimResponse entry (full-resource or id-only without the resource contents)
    # then update the fullUrl and id
    def update_tester_provided_notification_claim_response_entry(notification_bundle, claim_response_id,
                                                                 claim_response_full_url,
                                                                 existing_claim_response_reference)
      claim_response_entry = notification_bundle&.entry&.find { |e| e.resource&.resourceType == 'ClaimResponse' }
      if claim_response_entry.blank? && existing_claim_response_reference.present?
        claim_response_entry = notification_bundle&.entry&.find { |e| e.fullUrl == existing_claim_response_reference }
      end
      return unless claim_response_entry.present?

      claim_response_entry.fullUrl = claim_response_full_url
      return unless claim_response_entry.resource.present?

      claim_response_entry.resource.id = claim_response_id
    end

    def update_response_bundle(response_bundle, claim_full_url, now, ig_version)
      response_bundle.timestamp = now.iso8601 if response_bundle&.timestamp.present?
      if ig_version == 'v2.2.0' && response_bundle.identifier.blank?
        response_bundle.identifier = FHIR::Identifier.new(system: 'urn:ietf:rfc:3986',
                                                          value: "urn:uuid:#{SecureRandom.uuid}")
      end
      claim_response_entry = response_bundle&.entry&.find { |e| e&.resource&.resourceType == 'ClaimResponse' }
      return unless claim_response_entry.present?

      claim_response_entry.resource.created = now.iso8601 if claim_response_entry.resource.created
      return unless claim_full_url.present?

      if claim_response_entry.resource.request.present?
        claim_response_entry.resource.request.reference = claim_full_url
      elsif ig_version == 'v2.2.0'
        claim_response_entry.resource.request = FHIR::Reference.new(reference: claim_full_url)
      end
    end

    def build_mock_notification_bundle(notification_timestamp, subscription_reference, subscription_topic,
                                       submit_response, type, decision, _ig_version = 'v2.0.1')
      submit_response_bundle = FHIR.from_contents(submit_response)

      focus_reference, inner_bundle_full_url = determine_notification_focus(type, submit_response_bundle)

      mock_notification_bundle = FHIR::Bundle.new(
        id: SecureRandom.uuid,
        timestamp: notification_timestamp.iso8601,
        type: 'history'
      )

      mock_notification_status = build_mock_notification_status(notification_timestamp, subscription_reference,
                                                                subscription_topic, focus_reference, [])
      mock_notification_bundle.entry << build_mock_notification_status_entry(mock_notification_status,
                                                                             subscription_reference)

      add_notification_entries(mock_notification_bundle, submit_response_bundle, type, decision,
                               subscription_reference, inner_bundle_full_url)

      mock_notification_bundle
    end

    def determine_notification_focus(type, submit_response_bundle)
      if type == 'full-resource' && submit_response_bundle.is_a?(FHIR::Bundle)
        bundle_full_url = "urn:uuid:#{submit_response_bundle.id}"
        [bundle_full_url, bundle_full_url]
      else
        [claim_response_full_url_from_submit_response_bundle(submit_response_bundle), nil]
      end
    end

    def add_notification_entries(mock_notification_bundle, submit_response_bundle, type, decision,
                                 subscription_reference, inner_bundle_full_url)
      return unless type == 'full-resource' && submit_response_bundle.is_a?(FHIR::Bundle)

      claim_response_entry = submit_response_bundle.entry.find { |e| e.resource&.resourceType == 'ClaimResponse' }
      if claim_response_entry.present?
        update_claim_response_decisions(claim_response_entry.resource, decision)
        claim_response_entry.resource.outcome = 'complete'
      end

      fhir_base_url = extract_fhir_base_url(subscription_reference)
      mock_notification_bundle.entry << FHIR::Bundle::Entry.new(
        fullUrl: inner_bundle_full_url,
        resource: submit_response_bundle,
        request: FHIR::Bundle::Entry::Request.new(method: 'POST', url: "#{fhir_base_url}/Bundle"),
        response: FHIR::Bundle::Entry::Response.new(status: '201')
      )
    end

    def update_claim_response_decisions(claim_response, decision)
      claim_response&.item&.each do |item|
        item.adjudication.each do |adjudication|
          review_action_extension = adjudication.extension.find do |ext|
            ext.url == 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewAction'
          end
          review_code_extension = review_action_extension&.extension&.find do |ext|
            ext.url == 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewActionCode'
          end
          next unless review_code_extension.present?

          review_code_extension.valueCodeableConcept = FHIR::CodeableConcept.new(
            coding: [
              get_review_action_code(decision)
            ]
          )
        end
      end
    end

    def build_mock_response_bundle(request_bundle, operation, decision, timestamp, claim_response_uuid = nil,
                                   ig_version = 'v2.0.1')
      claim_entry = request_bundle&.entry&.find { |e| e&.resource&.resourceType == 'Claim' }
      claim_full_url = claim_entry&.fullUrl
      return nil if claim_entry.blank? || claim_full_url.blank?

      root_url = extract_fhir_base_url(claim_full_url)
      mocked_claim_response = build_mock_claim_response(claim_entry.resource, request_bundle, root_url, operation,
                                                        decision, timestamp, ig_version, claim_response_uuid,
                                                        claim_full_url)
      build_mock_bundle(mocked_claim_response, request_bundle, root_url, operation, timestamp, ig_version)
    end

    # Note that references from the claim to other resources in the bundle need to be changed to absolute URLs
    # if they are relative, because the ClaimResponse's fullUrl is a urn:uuid
    #
    # @private
    def build_mock_claim_response(claim, request_bundle, root_url, operation, decision, timestamp,
                                  ig_version = 'v2.0.1', claim_response_uuid = nil, claim_full_url = nil)
      claim_response_uuid = SecureRandom.uuid if claim_response_uuid.blank?
      return FHIR::ClaimResponse.new(id: claim_response_uuid) if claim.blank?

      FHIR::ClaimResponse.new(
        id: claim_response_uuid,
        meta: FHIR::Meta.new(profile: if operation == 'submit'
                                        "http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-claimresponse|#{ig_version.delete('v')}"
                                      else
                                        "http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-claiminquiryresponse|#{ig_version.delete('v')}"
                                      end),
        extension: ig_version == 'v2.2.0' ? [
          FHIR::Extension.new(
            url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-TransmissionIdentifiers',
            extension: [
              FHIR::Extension.new(url: 'applicationSenderCode', valueString: 'SENDER01'),
              FHIR::Extension.new(url: 'applicationReceiverCode', valueString: 'RECEIVER01')
            ]
          ),
          FHIR::Extension.new(
            url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-claimResponseReviewer',
            extension: [
              FHIR::Extension.new(url: 'wasHumanReviewedFlag', valueBoolean: true)
            ]
          )
        ] : [],
        identifier: claim.identifier,
        type: claim.type,
        status: claim.status,
        use: claim.use,
        patient: absolute_reference(claim.patient, request_bundle.entry, root_url),
        created: timestamp.iso8601,
        insurer: absolute_reference(claim.insurer, request_bundle.entry, root_url),
        requestor: absolute_reference(claim.provider, request_bundle.entry, root_url),
        request: claim_full_url.present? ? FHIR::Reference.new(reference: claim_full_url) : nil,
        # v2.2.0 removed 'queued' from ClaimResponseOutcome ValueSet; pended status is
        # conveyed via item.extension:reviewActionCode instead.
        outcome: (decision == :pended && ig_version != 'v2.2.0') ? 'queued' : 'complete',
        preAuthPeriod: FHIR::Period.new(
          start: timestamp.strftime('%Y-%m-%d'),
          end: (timestamp + 1.month).strftime('%Y-%m-%d')
        ),
        communicationRequest: [
          FHIR::Reference.new(display: 'Mock Communication Request')
        ],
        error: [
          FHIR::ClaimResponse::Error.new(
            extension: [
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-errorFollowupAction',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(system: 'https://codesystem.x12.org/005010/889', code: 'N')]
                )
              ),
              if ig_version == 'v2.2.0'
                # In v2.2.0 extension-errorElement is a complex extension; valueString is no longer allowed
                FHIR::Extension.new(
                  url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-errorElement',
                  extension: [
                    FHIR::Extension.new(url: 'error', valueString: 'ClaimResponse.status')
                  ]
                )
              else
                FHIR::Extension.new(
                  url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-errorElement',
                  valueString: 'ClaimResponse.status'
                )
              end,
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-errorPath',
                valueString: 'ClaimResponse.status'
              )
            ],
            code: FHIR::CodeableConcept.new(
              coding: [FHIR::Coding.new(system: 'https://codesystem.x12.org/005010/901', code: '04')]
            )
          )
        ],
        item: claim.item.map do |item|
          FHIR::ClaimResponse::Item.new(
            extension: [
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemPreAuthIssueDate',
                valueDate: timestamp.strftime('%Y-%m-%d')
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemPreAuthPeriod',
                valuePeriod: FHIR::Period.new(start: timestamp.strftime('%Y-%m-%d'),
                                              end: (timestamp + 1.month).strftime('%Y-%m-%d'))
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemTraceNumber',
                valueIdentifier: FHIR::Identifier.new(
                  system: 'https://prior-auth.davinci.hl7.org/fhir/ITEM_TRACE_NUMBER',
                  value: item.sequence.to_s
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-authorizationNumber',
                valueString: 'AUTH123'
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-administrationReferenceNumber',
                valueString: 'ADMIN123'
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemRequestedServiceDate',
                valuePeriod: FHIR::Period.new(start: timestamp.strftime('%Y-%m-%d'))
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemAuthorizedDetail',
                extension: [
                  FHIR::Extension.new(
                    url: 'productOrServiceCode',
                    valueCodeableConcept: FHIR::CodeableConcept.new(
                      coding: [FHIR::Coding.new(
                        system: 'https://codesystem.x12.org/005010/1365',
                        code: 'G0153'
                      )]
                    )
                  )
                ]
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemAuthorizedProvider',
                extension: [
                  FHIR::Extension.new(
                    url: 'provider',
                    valueReference: FHIR::Reference.new(display: 'Mock Provider')
                  )
                ]
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-communicatedDiagnosis',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(system: 'http://hl7.org/fhir/sid/icd-10-cm', code: 'J06.9')]
                )
              ),
              *(ig_version == 'v2.2.0' ? [
                FHIR::Extension.new(
                  url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-admissionDates',
                  valuePeriod: FHIR::Period.new(start: '2023-01-01')
                ),
                FHIR::Extension.new(
                  url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-dischargeDate',
                  valueDate: '2023-01-10'
                )
              ] : [])
            ],
            itemSequence: item.sequence,
            noteNumber: [1],
            adjudication: [
              FHIR::ClaimResponse::Item::Adjudication.new(
                extension: [
                  FHIR::Extension.new(
                    url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewAction',
                    extension: [
                      FHIR::Extension.new(
                        url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewActionCode',
                        valueCodeableConcept: FHIR::CodeableConcept.new(
                          coding: [
                            get_review_action_code(decision)
                          ]
                        )
                      )
                    ]
                  )
                ],
                category: FHIR::CodeableConcept.new(
                  coding: [
                    FHIR::Coding.new(system: 'http://terminology.hl7.org/CodeSystem/adjudication', code: 'submitted')
                  ]
                )
              )
            ]
          )
        end,
        addItem: ig_version == 'v2.2.0' ? [
          FHIR::ClaimResponse::AddItem.new(
            extension: [
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemTraceNumber',
                valueIdentifier: FHIR::Identifier.new(
                  system: 'https://prior-auth.davinci.hl7.org/fhir/ITEM_TRACE_NUMBER',
                  value: 'TRACE001'
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemPreAuthIssueDate',
                valueDate: timestamp.strftime('%Y-%m-%d')
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-itemPreAuthPeriod',
                valuePeriod: FHIR::Period.new(
                  start: timestamp.strftime('%Y-%m-%d'),
                  end: (timestamp + 1.month).strftime('%Y-%m-%d')
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-authorizationNumber',
                valueString: 'AUTH456'
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-administrationReferenceNumber',
                valueString: 'ADMIN456'
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-epsdtIndicator',
                valueBoolean: false
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-nursingHomeResidentialStatus',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(
                    system: 'https://valueset.x12.org/x217/005010/response/2000F/NX1/1/01/00/1345',
                    code: '2'
                  )]
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-nursingHomeLevelOfCare',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(
                    system: 'https://valueset.x12.org/x217/005010/response/2000F/NX1/1/02/00/1306',
                    code: '2'
                  )]
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-productOrServiceCodeEnd',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(system: 'https://codesystem.x12.org/005010/1365', code: 'G0153')]
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-revenueCode',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(system: 'https://www.nubc.org/CodeSystem/RevenueCodes', code: '0300')]
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-requestedService',
                valueReference: FHIR::Reference.new(display: 'Mock Requested Service')
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-admissionDates',
                valuePeriod: FHIR::Period.new(start: '2023-01-01')
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-dischargeDate',
                valueDate: '2023-01-10'
              )
            ],
            itemSequence: [1],
            provider: [
              FHIR::Reference.new(
                display: 'Mock AddItem Provider',
                extension: [
                  FHIR::Extension.new(
                    url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-authorizedProviderType',
                    valueCodeableConcept: FHIR::CodeableConcept.new(
                      coding: [FHIR::Coding.new(system: 'https://codesystem.x12.org/005010/98', code: 'IL')]
                    )
                  )
                ]
              )
            ],
            productOrService: FHIR::CodeableConcept.new(
              coding: [FHIR::Coding.new(system: 'https://codesystem.x12.org/005010/1365', code: 'G0153')]
            ),
            modifier: [
              FHIR::CodeableConcept.new(
                coding: [FHIR::Coding.new(system: 'http://www.ama-assn.org/go/cpt', code: '25')]
              )
            ],
            servicedDate: timestamp.strftime('%Y-%m-%d'),
            locationCodeableConcept: FHIR::CodeableConcept.new(
              coding: [FHIR::Coding.new(
                system: 'https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set',
                code: '11'
              )]
            ),
            quantity: FHIR::Quantity.new(value: 1),
            unitPrice: FHIR::Money.new(value: 100.0, currency: 'USD'),
            adjudication: [
              FHIR::ClaimResponse::Item::Adjudication.new(
                extension: [
                  FHIR::Extension.new(
                    url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewAction',
                    extension: [
                      FHIR::Extension.new(
                        url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewActionCode',
                        valueCodeableConcept: FHIR::CodeableConcept.new(
                          coding: [get_review_action_code(decision)]
                        )
                      )
                    ]
                  )
                ],
                category: FHIR::CodeableConcept.new(
                  coding: [
                    FHIR::Coding.new(system: 'http://terminology.hl7.org/CodeSystem/adjudication', code: 'submitted')
                  ]
                )
              )
            ]
          )
        ] : [],
        adjudication: ig_version == 'v2.2.0' ? [
          FHIR::ClaimResponse::Item::Adjudication.new(
            extension: [
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewAction',
                extension: [
                  # Neither 'code' (profiles extension-reviewActionCode, context excludes ClaimResponse.adjudication)
                  # nor 'reasonCode' (bound to X12278ReviewDecisionReasonCode, not review-action codes) can be
                  # used here without triggering a validator error. Use 'number' (plain string, no binding) to
                  # satisfy the MS check for extension-reviewAction on ClaimResponse.adjudication.
                  FHIR::Extension.new(url: 'number', valueString: '1')
                ]
              )
            ],
            category: FHIR::CodeableConcept.new(
              coding: [
                FHIR::Coding.new(system: 'http://terminology.hl7.org/CodeSystem/adjudication', code: 'submitted')
              ]
            )
          )
        ] : [],
        processNote: ig_version == 'v2.2.0' ? [
          FHIR::ClaimResponse::ProcessNote.new(
            number: 1,
            text: 'Prior authorization processing note'
          )
        ] : []
      )
    end

    def build_mock_bundle(claim_response, request_bundle, root_url, operation, timestamp, ig_version = 'v2.0.1')
      response_bundle = FHIR::Bundle.new(
        id: SecureRandom.uuid,
        meta: FHIR::Meta.new(profile: if operation == 'submit'
                                        "http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-pas-response-bundle|#{ig_version.delete('v')}"
                                      else
                                        "http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-pas-inquiry-response-bundle|#{ig_version.delete('v')}"
                                      end),
        identifier: if ig_version == 'v2.2.0'
                      FHIR::Identifier.new(
                        system: 'urn:ietf:rfc:3986',
                        value: "urn:uuid:#{SecureRandom.uuid}"
                      )
                    end,
        timestamp: timestamp.iso8601,
        type: 'collection',
        entry: [
          FHIR::Bundle::Entry.new(fullUrl: "urn:uuid:#{claim_response.id}",
                                  resource: claim_response)
        ]
      )
      response_bundle.entry.concat(referenced_entities(claim_response, request_bundle.entry, root_url))

      if ig_version == 'v2.2.0' && operation == 'submit'
        comm_request = build_mock_communication_request
        comm_full_url = "urn:uuid:#{comm_request.id}"
        response_bundle.entry << FHIR::Bundle::Entry.new(fullUrl: comm_full_url, resource: comm_request)
        claim_response.communicationRequest = [FHIR::Reference.new(reference: comm_full_url)]
      end

      if ig_version == 'v2.2.0'
        task = build_mock_task
        response_bundle.entry << FHIR::Bundle::Entry.new(fullUrl: "urn:uuid:#{task.id}", resource: task)

        practitioner = build_mock_practitioner
        pract_full_url = "urn:uuid:#{practitioner.id}"
        response_bundle.entry << FHIR::Bundle::Entry.new(fullUrl: pract_full_url, resource: practitioner)

        practitioner_role = build_mock_practitioner_role(pract_full_url)
        pract_role_full_url = "urn:uuid:#{practitioner_role.id}"
        response_bundle.entry << FHIR::Bundle::Entry.new(fullUrl: pract_role_full_url, resource: practitioner_role)
      end

      response_bundle
    end

    def build_mock_communication_request
      FHIR::CommunicationRequest.new(
        id: SecureRandom.uuid,
        meta: FHIR::Meta.new(
          profile: ['http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-communicationrequest']
        ),
        extension: [
          FHIR::Extension.new(
            url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-serviceLineNumber',
            valuePositiveInt: 1
          )
        ],
        identifier: [
          FHIR::Identifier.new(system: 'http://davinci-pas.org/fhir/comm-req-id', value: 'COMM001')
        ],
        status: 'active',
        category: [
          FHIR::CodeableConcept.new(
            coding: [FHIR::Coding.new(
              system: 'https://codesystem.x12.org/005010/755',
              code: '15',
              display: 'Justification for Admissions'
            )]
          )
        ],
        medium: [
          FHIR::CodeableConcept.new(
            coding: [FHIR::Coding.new(
              system: 'http://terminology.hl7.org/CodeSystem/v3-ParticipationMode',
              code: 'WRITTEN'
            )]
          )
        ],
        subject: FHIR::Reference.new(display: 'Mock Patient'),
        payload: [
          FHIR::CommunicationRequest::Payload.new(
            extension: [
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-communicatedDiagnosis',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(system: 'http://hl7.org/fhir/sid/icd-10-cm', code: 'J06.9')]
                )
              ),
              FHIR::Extension.new(
                url: 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-contentModifier',
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(system: 'http://loinc.org', code: '18804-5')]
                )
              )
            ],
            contentString: '18776-5'
          )
        ],
        requester: FHIR::Reference.new(display: 'Mock Requester'),
        recipient: [FHIR::Reference.new(display: 'Mock Recipient')],
        sender: FHIR::Reference.new(display: 'Mock Sender')
      )
    end

    def build_mock_practitioner
      FHIR::Practitioner.new(
        id: SecureRandom.uuid,
        meta: FHIR::Meta.new(
          profile: ['http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-practitioner']
        ),
        identifier: [
          FHIR::Identifier.new(
            system: 'http://hl7.org/fhir/sid/us-npi',
            value: '1234567893'
          )
        ],
        name: [
          FHIR::HumanName.new(family: 'WATSON', given: ['SUSAN'])
        ],
        address: [
          FHIR::Address.new(
            line: ['123 Main St'],
            city: 'Springfield',
            state: 'IL',
            postalCode: '62701',
            country: 'US'
          )
        ],
        telecom: [
          FHIR::ContactPoint.new(system: 'phone', value: '5555550100')
        ]
      )
    end

    def build_mock_practitioner_role(practitioner_full_url)
      FHIR::PractitionerRole.new(
        id: SecureRandom.uuid,
        meta: FHIR::Meta.new(
          profile: ['http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-practitionerrole']
        ),
        practitioner: FHIR::Reference.new(reference: practitioner_full_url),
        organization: FHIR::Reference.new(display: 'Mock Organization'),
        code: [
          FHIR::CodeableConcept.new(
            coding: [FHIR::Coding.new(
              system: 'http://nucc.org/provider-taxonomy',
              code: '208D00000X',
              display: 'General Practice Physician'
            )]
          )
        ],
        specialty: [
          FHIR::CodeableConcept.new(
            coding: [FHIR::Coding.new(
              system: 'http://nucc.org/provider-taxonomy',
              code: '208D00000X',
              display: 'General Practice Physician'
            )]
          )
        ],
        location: [FHIR::Reference.new(display: 'Mock Location')],
        endpoint: [FHIR::Reference.new(display: 'Mock Endpoint')],
        telecom: [
          FHIR::ContactPoint.new(system: 'phone', value: '5555550100')
        ]
      )
    end

    def build_mock_task
      pas_temp = 'http://hl7.org/fhir/us/davinci-pas/CodeSystem/PASTempCodes'
      sln_url = 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-serviceLineNumber'
      cm_url = 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-contentModifier'

      FHIR::Task.new(
        id: SecureRandom.uuid,
        meta: FHIR::Meta.new(
          profile: ['http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-task']
        ),
        identifier: [
          FHIR::Identifier.new(system: 'http://example.org/ITEM_TRACE_NUMBER', value: 'TASK001')
        ],
        status: 'requested',
        statusReason: FHIR::CodeableConcept.new(
          coding: [FHIR::Coding.new(
            system: pas_temp,
            code: 'priorAuthorization'
          )]
        ),
        intent: 'order',
        code: FHIR::CodeableConcept.new(
          coding: [FHIR::Coding.new(system: pas_temp, code: 'attachment-request-code')]
        ),
        for: FHIR::Reference.new(display: 'Mock Patient'),
        requester: FHIR::Reference.new(
          identifier: FHIR::Identifier.new(system: 'http://hl7.org/fhir/sid/us-npi', value: '1234567893')
        ),
        owner: FHIR::Reference.new(
          identifier: FHIR::Identifier.new(system: 'http://hl7.org/fhir/sid/us-npi', value: '1234567893')
        ),
        reasonCode: FHIR::CodeableConcept.new(
          coding: [FHIR::Coding.new(system: pas_temp, code: 'priorAuthorization')]
        ),
        reasonReference: FHIR::Reference.new(display: 'Mock Claim'),
        restriction: FHIR::Task::Restriction.new(
          period: FHIR::Period.new(start: '2023-01-01', end: '2023-12-31')
        ),
        input: [
          FHIR::Task::Input.new(
            type: FHIR::CodeableConcept.new(
              coding: [FHIR::Coding.new(system: pas_temp, code: 'payer-url')]
            ),
            valueUrl: 'http://example.org/payerURL'
          ),
          FHIR::Task::Input.new(
            extension: [
              FHIR::Extension.new(url: sln_url, valuePositiveInt: 1),
              FHIR::Extension.new(
                url: cm_url,
                valueCodeableConcept: FHIR::CodeableConcept.new(
                  coding: [FHIR::Coding.new(system: 'http://loinc.org', code: '18804-5')]
                )
              )
            ],
            type: FHIR::CodeableConcept.new(
              coding: [FHIR::Coding.new(system: pas_temp, code: 'attachments-needed')]
            ),
            valueCodeableConcept: FHIR::CodeableConcept.new(
              coding: [FHIR::Coding.new(system: 'http://loinc.org', code: '28570-0')]
            )
          ),
          FHIR::Task::Input.new(
            extension: [
              FHIR::Extension.new(url: sln_url, valuePositiveInt: 1)
            ],
            type: FHIR::CodeableConcept.new(
              coding: [FHIR::Coding.new(system: pas_temp, code: 'questionnaire-context')]
            ),
            valueString: 'http://example.org/questionnaire'
          )
        ]
      )
    end

    def build_mock_notification_status_entry(status_parameters, subscription_reference)
      FHIR::Bundle::Entry.new(fullUrl: "urn:uuid:#{SecureRandom.uuid}",
                              resource: status_parameters,
                              request: FHIR::Bundle::Entry::Request.new(
                                method: 'GET',
                                url: "#{subscription_reference}/$status"
                              ),
                              response: FHIR::Bundle::Entry::Response.new(
                                status: '200'
                              ))
    end

    def build_mock_notification_status(timestamp, subscription_reference, subscription_topic, claim_response_reference,
                                       additional_context_references)
      status_parameters = FHIR::Parameters.new
      status_parameters.parameter << FHIR::Parameters::Parameter.new(
        name: 'subscription',
        valueReference: FHIR::Reference.new(
          reference: subscription_reference
        )
      )
      status_parameters.parameter << FHIR::Parameters::Parameter.new(
        name: 'topic',
        valueCanonical: subscription_topic
      )
      status_parameters.parameter << FHIR::Parameters::Parameter.new(
        name: 'status',
        valueCode: 'active'
      )
      status_parameters.parameter << FHIR::Parameters::Parameter.new(
        name: 'type',
        valueCode: 'event-notification'
      )
      status_parameters.parameter << FHIR::Parameters::Parameter.new(
        name: 'events-since-subscription-start',
        valueString: '1'
      )
      if claim_response_reference.present?
        event = FHIR::Parameters::Parameter.new(
          name: 'notification-event'
        )
        status_parameters.parameter << event
        event.part << FHIR::Parameters::Parameter.new(
          name: 'event-number',
          valueString: '1'
        )
        event.part << FHIR::Parameters::Parameter.new(
          name: 'timestamp',
          valueInstant: timestamp.iso8601
        )
        event.part << FHIR::Parameters::Parameter.new(
          name: 'focus',
          valueReference: FHIR::Reference.new(
            reference: claim_response_reference
          )
        )
        additional_context_references&.each do |reference|
          event.part << FHIR::Parameters::Parameter.new(
            name: 'additional-context',
            valueReference: FHIR::Reference.new(
              reference:
            )
          )
        end
      end
      status_parameters
    end

    def get_review_action_code(decision)
      case decision
      when :denial
        code = 'A3'
        display = 'Not Certified'
      when :pended
        code = 'A4'
        display = 'Pending'
      else # approval or no workflow
        code = 'A1'
        display = 'Certified in total'
      end
      FHIR::Coding.new(
        system: 'https://codesystem.x12.org/005010/306',
        code:,
        display:
      )
    end

    def absolute_reference(ref, entries, root_url)
      url = find_matching_entry(ref&.reference, entries, root_url)&.fullUrl
      ref.reference = url if url
      ref
    end

    def referenced_entities(resource, entries, root_url, matches = [])
      attributes = resource&.source_hash&.keys
      attributes&.each do |attr|
        if attr.to_s == 'request' && resource.respond_to?(:resourceType) && resource.resourceType == 'ClaimResponse'
          next
        end

        value = resource.send(attr.to_sym)
        if value.is_a?(FHIR::Reference) && value.reference.present?
          match = find_matching_entry(value.reference, entries, root_url)
          if match.present? && matches.none? { |m| m.fullUrl == match.fullUrl }
            value.reference = match.fullUrl
            matches << match
            referenced_entities(match.resource, entries, root_url, matches)
          end
        elsif value.is_a?(Array) && value.all? { |elmt| elmt.is_a?(FHIR::Model) }
          value.each { |val| referenced_entities(val, entries, root_url, matches) }
        end
      end

      matches
    end

    def find_matching_entry(ref, entries, root_url = '')
      ref = "#{root_url}/#{ref}" if relative_reference?(ref) && root_url&.present?

      entries&.find { |entry| entry&.fullUrl == ref }
    end

    def relative_reference?(ref)
      ref&.count('/') == 1
    end

    # Drop the last two segments of a URL, i.e. the resource type and ID of a FHIR resource
    # e.g. http://example.org/fhir/Patient/123 -> http://example.org/fhir
    def extract_fhir_base_url(url)
      return unless url&.start_with?('http://', 'https://')

      # Drop everything after the second to last '/', ignoring a trailing slash
      url.sub(%r{/[^/]*/[^/]*(/)?\z}, '')
    end

    def claim_response_full_url_from_submit_response_bundle(submit_response_bundle)
      submit_response_bundle = submit_response_bundle.parameter[0] if submit_response_bundle.is_a?(FHIR::Parameters)

      claim_response_entry = submit_response_bundle&.entry&.find { |e| e&.resource&.resourceType == 'ClaimResponse' }

      if claim_response_entry.present?
        return claim_response_entry.fullUrl unless claim_response_entry.fullUrl.blank?
        unless claim_response_entry.resource.blank? || claim_response_entry.resource.id.blank?
          return claim_response_entry.resource.id
        end
      end
      "urn:uuid:#{SecureRandom.uuid}"
    end

    # Wraps a Bundle in a Parameters resource for v2.2.0 inquire responses
    # @param bundle [FHIR::Bundle] The Bundle to wrap
    # @return [FHIR::Parameters] Parameters resource with the bundle as a return parameter
    def wrap_bundle_in_parameters(bundle)
      return nil unless bundle.is_a?(FHIR::Bundle)

      parameters = FHIR::Parameters.new
      parameters.parameter << FHIR::Parameters::Parameter.new(
        name: 'return',
        resource: bundle
      )
      parameters
    end
  end
end
