require_relative 'davinci_pas_test_kit/metadata'
require_relative 'davinci_pas_test_kit/client/v2.0.1/client_suite'
require_relative 'davinci_pas_test_kit/client/v2.2.1/client_suite'
require_relative 'davinci_pas_test_kit/server/generated/v2.0.1/server_suite'
require_relative 'davinci_pas_test_kit/server/generated/v2.2.1/server_suite'
