require_relative '../urls'
require_relative '../../client_input_descriptions'
require_relative '../../user_input_response'
require_relative '../../subscription_notification_trigger'
require_relative '../../../cross_suite/tags'
require_relative '../../../cross_suite/fhirpath_utils'

module DaVinciPASTestKit
  module DaVinciPASV221
    class PASClientPendedNotifyAndAttestFinalizedTest < Inferno::Test
      include URLs
      include UserInputResponse
      include SubscriptionNotificationTrigger
      include FhirpathUtils

      id :pas_client_v221_pended_notify_and_attest_finalized_test
      title 'Inferno sends a notification that the pended request has been finalized'
      description %(
        During this test, Inferno will send a full-resource notification to the client's Subscription
        endpoint to tell it that a final decision has been made on the pended prior authorization request
        that the client submitted earlier. The notification is generated from the pended `$submit` response
        that Inferno returned to the client, unless one is provided.
      )

      input :notification_bundle,
            title: 'Claim updated notification JSON',
            type: 'textarea',
            optional: true,
            description: DaVinciPASTestKit.notification_bundle_input_description(full_resource_required: true)
      input :pended_json_response,
            title: 'Claim pended response JSON',
            type: 'textarea',
            optional: true,
            description: DaVinciPASTestKit.user_response_input_description('$submit', 'pended', 'Pended Response')
      input :client_endpoint_access_token,
            optional: true,
            title: 'Client Notification Access Token',
            description: INPUT_CLIENT_ENDPOINT_ACCESS_TOKEN

      run do
        subscription_request = load_tagged_requests(SUBSCRIPTION_CREATE_TAG).find { |req| req.status == 201 }
        skip_if subscription_request.blank?, # NOTE: subscription needed to support notification generation
                %(
                  No Subscription exists to receive the notification. Run the _PAS Subscription Setup_ tests to
                  provide a Subscription for use in delivering notifications before re-running the pended
                  scenario tests.
                )
        @subscription_json = JSON.parse(subscription_request.response_body)

        pended_submit_requests = load_tagged_requests(SUBMIT_TAG, PENDED_WORKFLOW_TAG)
        @pended_submit_request = pended_submit_requests.select { |req| req.status == 200 }.max_by(&:index)
        skip_if @pended_submit_request.blank?,
                'The client made no successful $submit request during the pended scenario, so there is no pended ' \
                'response to send a notification about.'

        if notification_bundle.present?
          assert_valid_json notification_bundle, "Input '#{input_title(:notification_bundle)}' must be valid JSON"
        else
          add_message('info', %(
            No notification body provided in input '#{input_title(:notification_bundle)}'. The notification finalizing
            the pended $submit response will be generated by Inferno from the pended response.
          ))
        end

        start_notification_job(@pended_submit_request.response_body, :approval, generated_claim_response_uuid,
                               resume_test: true)

        wait(
          identifier: test_session_id,
          timeout: 300,
          message: <<~MESSAGE
            **Pended Scenario Test**:

            Inferno will shortly send a full-resource notification to the endpoint specified in the client's
            Subscription to tell it that a final decision has been made on the pended prior authorization
            request. The tests will continue automatically once the notification has been sent.
          MESSAGE
        )
      end

      # The id of the ClaimResponse Inferno generated for the pended $submit response, which tells the module to
      # point the notification at it. Nil when the tester provided the response and is responsible for the
      # notification matching it.
      def generated_claim_response_uuid
        return if pended_json_response.present?

        claim_response_entry = FHIR.from_contents(@pended_submit_request.response_body)&.entry&.find do |entry|
          entry.resource&.resourceType == 'ClaimResponse'
        end
        claim_response_entry&.fullUrl&.delete_prefix('urn:uuid:')
      end

      # Helper methods for SubscriptionNotificationTrigger. The job looks up the test run and result once
      # this test is waiting, because they do not exist yet while it runs.

      def notification_test_run_id
        nil
      end

      def notification_test_session_id
        test_session_id
      end

      def notification_result_id
        nil
      end

      def notification_bearer_token
        client_endpoint_access_token
      end

      # Replaces {{fhirpath}} tokens in the tester-provided notification body using values from the
      # $submit request the notification is finalizing, the same way as a tester-provided response
      # candidate. If a replaced value breaks the JSON structure, nil is returned with a warning so
      # that Inferno generates a notification instead (see SubscriptionNotificationTrigger#notification_json).
      def tester_notification_bundle
        return if notification_bundle.blank?

        replace_tokens_and_normalize(notification_bundle, submitted_claim_bundle)
      rescue JSON::ParserError
        add_message('warning',
                    'Unable to use the provided notification body, so Inferno will generate one instead. The ' \
                    'notification is not valid JSON after {{fhirpath}} token replacement, for example because a ' \
                    'token value contains a double quote.')
        nil
      end

      def submitted_claim_bundle
        return @submitted_claim_bundle if defined?(@submitted_claim_bundle)

        request_body = @pended_submit_request&.request_body
        @submitted_claim_bundle = request_body.present? ? FHIR.from_contents(request_body) : nil
      end

      def client_subscription_json
        @subscription_json
      end

      # the job ends the wait using this token
      def test_run_identifier
        test_session_id
      end

      def ig_version
        'v2.2.1'
      end
    end
  end
end
