require_relative '../../../cross_suite/tags'

module DaVinciPASTestKit
  module DaVinciPASV221
    class PasClientModificationVerificationTest < Inferno::Test
      id :pas_client_v221_modification_verification_test
      title '$submit response represents a payer modification'
      description %(
        In PAS v2.2.1, a payer may authorize items that differ from those that were requested. This test
        verifies that the response returned for the $submit request represents such a payer modification by
        checking that:

        - at least one `ClaimResponse.item` entry has an adjudication review action code of A6 ('Modified'), and
        - each modified item is paired with a `ClaimResponse.addItem` entry that references it via the same
          `itemSequence` value, conveying the details of what was actually authorized.

        The response checked here is either the response body provided by the tester in the corresponding
        input or the one generated by Inferno from the $submit Bundle.
      )
      simulation_verification

      REVIEW_ACTION_URL =
        'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewAction'.freeze
      REVIEW_ACTION_CODE_URL =
        'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-reviewActionCode'.freeze
      MODIFIED_REVIEW_ACTION_CODE = 'A6'.freeze

      run do
        load_tagged_requests(MODIFICATION_WORKFLOW_TAG, SUBMIT_TAG)
        skip_if requests.empty?, 'No responses to verify because no submit requests were made.'

        # Log findings directly to the result rather than asserting inline so that every issue
        # across all received responses is reported in a single run instead of halting on the first.
        requests.each { |submit_request| check_modification_response(submit_request) }

        assert_no_error_messages('The $submit response does not represent a payer modification. ' \
                                 'See Messages for details.')
      end

      def check_modification_response(submit_request)
        claim_response = claim_response_from_response_body(submit_request.response_body)
        if claim_response.blank?
          add_message('error', 'No ClaimResponse was found in the $submit response.')
          return
        end

        modified_sequences = modified_item_sequences(claim_response)
        if modified_sequences.blank?
          add_message('error',
                      'Expected at least one ClaimResponse.item entry with an adjudication review action code of ' \
                      "'#{MODIFIED_REVIEW_ACTION_CODE}' (Modified), but none were found.")
        end

        add_item_sequences = Array(claim_response.addItem).flat_map { |add_item| Array(add_item.itemSequence) }
        missing = modified_sequences.reject { |sequence| add_item_sequences.include?(sequence) }
        return if missing.empty?

        add_message('error',
                    'Each modified item must be paired with a ClaimResponse.addItem entry that has the same ' \
                    "itemSequence. No matching addItem was found for itemSequence(s): #{missing.join(', ')}.")
      end

      # Extracts the ClaimResponse from a $submit response body, unwrapping the Parameters resource
      # that wraps the Bundle for v2.2.1 inquire responses if one is present.
      def claim_response_from_response_body(response_body)
        resource = FHIR.from_contents(response_body)
        return if resource.blank?

        bundle =
          if resource.is_a?(FHIR::Parameters)
            resource.parameter&.map(&:resource)&.find { |r| r.is_a?(FHIR::Bundle) }
          else
            resource
          end
        return unless bundle.is_a?(FHIR::Bundle)

        bundle.entry&.map(&:resource)&.find { |r| r.is_a?(FHIR::ClaimResponse) }
      end

      def modified_item_sequences(claim_response)
        Array(claim_response.item).select { |item| item_modified?(item) }.map(&:itemSequence).compact
      end

      def item_modified?(item)
        Array(item.adjudication).any? { |adjudication| adjudication_modified?(adjudication) }
      end

      def adjudication_modified?(adjudication)
        review_action = Array(adjudication.extension).find { |ext| ext.url == REVIEW_ACTION_URL }
        return false if review_action.blank?

        review_action_code = Array(review_action.extension).find { |ext| ext.url == REVIEW_ACTION_CODE_URL }
        return false if review_action_code&.valueCodeableConcept.blank?

        Array(review_action_code.valueCodeableConcept.coding).any? do |coding|
          coding.code == MODIFIED_REVIEW_ACTION_CODE
        end
      end
    end
  end
end
