require_relative '../urls'
require_relative '../../client_input_descriptions'
require_relative '../../user_input_response'
require_relative '../../../cross_suite/pas_bundle_validation'
require_relative '../../session_identification'
require_relative '../../subscription_setup_requirement'

module DaVinciPASTestKit
  module DaVinciPASV221
    class PASClientPendedSubmitTest < Inferno::Test
      include URLs
      include SessionIdentification
      include UserInputResponse
      include PasBundleValidation
      include SubscriptionSetupRequirement

      id :pas_client_v221_pended_submit_test
      title 'PAS client submits a claim using the $submit operation'
      description %(
        During this test, Inferno will wait for a prior authorization submission request
        from the client using the `$submit` operation. Upon receipt, Inferno will respond
        with a [tester-provided](https://github.com/inferno-framework/davinci-pas-test-kit/wiki/Controlling-Simulated-Responses#tester-directed-custom-responses)
        or [Inferno-mocked](https://github.com/inferno-framework/davinci-pas-test-kit/wiki/Controlling-Simulated-Responses#mocked-responses)
        pended response. Inferno will not respond to `$inquire` operation requests during
        this test.
      )

      input :pended_json_response,
            title: 'Claim pended response JSON',
            type: 'textarea',
            optional: true,
            description: DaVinciPASTestKit.user_response_input_description('$submit', 'pended', 'Pended Scenario')
      input :client_id,
            title: 'Client Id',
            type: 'text',
            optional: true,
            locked: true,
            description: INPUT_CLIENT_ID_LOCKED
      input :session_url_path,
            title: 'Session-specific URL path extension',
            type: 'text',
            optional: true,
            locked: true,
            description: INPUT_SESSION_URL_PATH_LOCKED

      submit_respond_with :pended_json_response
      config options: { submit_enabled: true, suppress_notifications: true } # handling notification separately
      output :confirmation_url

      run do
        require_successful_subscription_create_request

        if user_inputted_response? :pended_json_response
          assert_valid_json pended_json_response,
                            "Input '#{input_title(:pended_json_response)}' must be valid JSON"
        else
          add_message('info', %(
            No pended response provided in input '#{input_title(:pended_json_response)}'. Any responses to $submit
            requests will be generated by Inferno from the submitted Claim.
          ))
        end

        wait_identifier = session_wait_identifier(client_id, session_url_path)
        submit_endpoint = session_endpoint_url(:submit, client_id, session_url_path)
        confirmation_url = "#{resume_pass_url}?token=#{wait_identifier}"
        output(confirmation_url:)

        wait(
          identifier: wait_identifier,
          message: <<~MESSAGE
            **Pended Scenario Test**:

            Inferno will wait while the tester uses the client system to submit a PAS request to
            Inferno. The tests will automatically continue once a request has been received.

            ### Endpoints

            Submit a PAS request to

            `#{submit_endpoint}`

            ### Authentication and Identification

            #{auth_description_for_wait(client_id)}

            ### Responses

            #{response_description_for_wait(user_inputted_response?(:pended_json_response),
                                            input_title(:pended_json_response),
                                            '$submit')}

            Inferno will not respond to `$inquire` requests during this test.
          MESSAGE
        )
      end
    end
  end
end
