require_relative '../urls'
require_relative '../../client_input_descriptions'
require_relative '../../user_input_response'
require_relative '../../subscription_notification_trigger'
require_relative '../../subscription_setup_requirement'
require_relative '../../../cross_suite/tags'

module DaVinciPASTestKit
  module DaVinciPASV221
    class PASClientPendedNotifyAndAttestFinalizedTest < Inferno::Test
      include URLs
      include UserInputResponse
      include SubscriptionNotificationTrigger
      include SubscriptionSetupRequirement

      id :pas_client_v221_pended_notify_and_attest_finalized_test
      title 'Inferno sends a notification that the pended request has been finalized'
      description %(
        During this test, Inferno will send a full-resource notification to the client's Subscription
        endpoint to tell it that a final decision has been made on the pended prior authorization request
        that the client submitted earlier. The notification is generated from the pended `$submit` response
        that Inferno returned to the client, unless one is provided.
      )

      input :notification_bundle,
            title: 'Claim updated notification JSON',
            type: 'textarea',
            optional: true,
            description: %(
              If provided, this JSON will be sent as the notification for the
              PAS Subscription to tell the client that a decision has been made on the pended claim.
              Before sending, Inferno will update the provided notification with details that the tester cannot
              know ahead of time, including timestamps corresponding to the notification trigger time, and the id of
              the triggering ClaimResponse if Inferno mocks that ClaimResponse because it is not provided by the
              tester through the *Claim pended response JSON* input.
              If not provided, a notification will be generated from the returned ClaimResponse.
              In either case the response will be validated to ensure that the notification
              is conformant. For PAS v2.2.1, the notification must be a full-resource notification
              containing the complete ClaimResponse.
            )
      input :pended_json_response,
            title: 'Claim pended response JSON',
            type: 'textarea',
            optional: true,
            description: DaVinciPASTestKit.user_response_input_description('$submit', 'pended', 'Pended Response')
      input :client_endpoint_access_token,
            optional: true,
            title: 'Client Notification Access Token',
            description: %(
              The bearer token that Inferno will send on requests to the client system's rest-hook notification
              endpoint. Not needed if the client system will create a Subscription with an appropriate header value
              in the `channel.header` element. If a value for the `authorization` header is provided in
              `channel.header`, this value will override it.
            )

      run do
        subscription_request = require_successful_subscription_create_request
        @subscription_json = JSON.parse(subscription_request.response_body)

        pended_submit_requests = load_tagged_requests(SUBMIT_TAG, PENDED_WORKFLOW_TAG)
        @pended_submit_request = pended_submit_requests.select { |req| req.status == 200 }.max_by(&:index)
        skip_if @pended_submit_request.blank?,
                'The client made no successful $submit request during the pended scenario, so there is no pended ' \
                'response to send a notification about.'

        if notification_bundle.present?
          assert_valid_json notification_bundle, "Input '#{input_title(:notification_bundle)}' must be valid JSON"
        else
          add_message('info', %(
            No notification body provided in input '#{input_title(:notification_bundle)}'. The notification finalizing
            the pended $submit response will be generated by Inferno from the pended response.
          ))
        end

        start_notification_job(@pended_submit_request.response_body, :approval, generated_claim_response_uuid,
                               resume_test: true)

        wait(
          identifier: test_run_identifier,
          timeout: Jobs::SendPASSubscriptionNotification::TEST_WAIT_TIMEOUT_SECONDS,
          message: <<~MESSAGE
            **Pended Scenario Test**:

            Inferno will shortly send a full-resource notification to the endpoint specified in the client's
            Subscription to tell it that a final decision has been made on the pended prior authorization
            request. The tests will continue automatically once the notification has been sent.
          MESSAGE
        )
      end

      # The id of the ClaimResponse Inferno generated for the pended $submit response, which tells the module to
      # point the notification at it. Nil when the tester provided the response and is responsible for the
      # notification matching it.
      def generated_claim_response_uuid
        return if pended_json_response.present?

        response_bundle = FHIR.from_contents(@pended_submit_request.response_body)
        claim_response_entry_from_response_bundle(response_bundle)&.fullUrl&.delete_prefix('urn:uuid:')
      end

      # Helper methods for SubscriptionNotificationTrigger. The job looks up the test run and result once
      # this test is waiting, because they do not exist yet while it runs.

      def notification_test_run_id
        nil
      end

      def notification_test_session_id
        test_session_id
      end

      def notification_result_id
        nil
      end

      def notification_bearer_token
        client_endpoint_access_token
      end

      def tester_notification_bundle
        notification_bundle
      end

      def client_subscription_json
        @subscription_json
      end

      # Only the job continues this wait, so it uses a fresh random identifier - see SessionIdentification.
      # Memoized because start_notification_job passes it to the job before wait registers it.
      def test_run_identifier
        @test_run_identifier ||= SecureRandom.uuid
      end

      def ig_version
        'v2.2.1'
      end
    end
  end
end
